### ISSUE TITLE
gcc/ld errors when compiling with EESSI modules

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#26]
I was trying to compile some C code, and ran into the following issues:
```
$ gcc hello.c -o hello
/usr/bin/ld.gold: --push-state: unknown option
/usr/bin/ld.gold: use the --help option for usage information
collect2: error: ld returned 1 exit status

$ which -a ld.gold
/usr/bin/ld.gold
/bin/ld.gold
```
We somehow need to instruct gcc to use the one from the compatibility layer.

**Comment by bedroge** [comment]
I had a look at how CC does this, and they do add `$EPREFIX/usr/bin` to `$PATH`:

```
Singularity> source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
Singularity> ml StdEnv/2020 
Singularity> ml gcc/9.3.0
Singularity> echo $PATH
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/openmpi/4.0.3/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/libfabric/1.10.1/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/ucx/1.8.0/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin:/cvmfs/soft.computecanada.ca/easybuild/bin:/cvmfs/soft.computecanada.ca/custom/bin:/cvmfs/soft.computecanada.ca/gentoo/2020/usr/sbin:/cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin:/cvmfs/soft.computecanada.ca/gentoo/2020/sbin:/cvmfs/soft.computecanada.ca/gentoo/2020/bin:/cvmfs/soft.computecanada.ca/custom/bin/computecanada:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Singularity> which ld
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/ld

```

**Comment by boegel** [comment]
@bedroge Hmm, but then we pick up *everything* from Gentoo Prefix, including stuff like `vim` and even `ls` & co...

**Comment by bedroge** [comment]
Yep, I don't really like that either (although it's maybe less of a big deal than it seems?), so it would be nice if we can come up with some other solution.

**Comment by boegel** [comment]
It looks like `${COMPILER_PATH}` could be the correct way of dealing with this...

This works to tell GCC to use tools from the compat layer rather than using those provided in `/usr/bin` on the host:

```
export COMPILER_PATH=${EPREFIX}/usr/bin
gcc hello.c -o hello
```

Setting `$GCC_EXEC_PREFIX` does not work, since that prevents GCC from falling back to its own installation prefix for `cc1`:

```
$ export GCC_EXEC_PREFIX=$EPREFIX/usr/bin
$ gcc hello.c -o hello
gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
```

(see also https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/Environment-Variables.html)

**Comment by migueldiascosta** [comment]
if there are any cases where setting `${COMPILER_PATH}` is not enough (e.g., scripts calling the tools directly?), maybe `${EPREFIX}/usr/x86_64-pc-linux-gnu/bin/` (links to binutils-bin) can safely be added to `PATH`? (and eventually build these binutils with RPATH to make them completely independent of the host?)

**Comment by migueldiascosta** [comment]
apparently, using RPATH is not necessary in prefix-standalone, which is the one being used:

 "The runtime dynamic loader, shipped with Prefix glibc, looks into Prefix for dynamic libraries. The compiler is modified so that produced binary has dynamic loader field pointed to the one in Prefix" (from https://wiki.gentoo.org/wiki/Project:Prefix/Technical_Documentation)

So it should be safe to include in PATH (selected) binaries from the prefix. 

Perhaps add to the PATH a folder with links to the prefix binaries of all the dependencies filtered from the easybuilt stack? https://github.com/EESSI/software-layer/blob/c8bd7ec73fe8effe9c163b8345c62f5eab51fddd/EESSI-pilot-install-software.sh#L96
